spring:
  datasource:
    url: jdbc:mysql://localhost:3307/todolist?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: myblog
    password: myblog123!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: mysecretkeymysecretkeymysecretkey1234
