version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-todolist
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1q2w3e4r
      MYSQL_DATABASE: todolist
      MYSQL_USER: myblog
      MYSQL_PASSWORD: myblog123!
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
